{
  "openapi": "3.0.1",
  "info": {
    "version": "2.0.1",
    "title": "Petly back-end",
    "description": "i have to write some description here",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "servers": [
    { "url": "https://petly-5jqe.onrender.com/api" },
    { "url": "http://localhost:3000/api" }
  ],
  "tags": [
    {
      "name": "auth",
      "description": "authorization"
    },
    {
      "name": "services-sidebar",
      "description": "Petly's friends"
    },
    {
      "name": "news",
      "description": "Petly's news"
    },
    {
      "name": "notices",
      "description": "Notices about pets"
    },
    {
      "name": "user",
      "description": "Privat information about user"
    }
  ],
  "paths": {
    "/users/signup": {
      "post": {
        "tags": ["auth"],
        "summary": "User registration",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserSignupRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserSignupResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "409": {
            "description": "Provided email already exists",
            "content": {}
          }
        }
      }
    },
    "/users/new_password": {
      "post": {
        "tags": ["auth"],
        "summary": "User forgot password",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserNewPasswordRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserNewPasswordResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {}
          }
        }
      }
    },
    "/users/verify/:verificationToken": {
      "get": {
        "tags": ["auth"],
        "summary": "User's verifing email",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserVerifyResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      }
    },
    "/users/verify": {
      "post": {
        "tags": ["auth"],
        "summary": "User's verifing email",
        "parameters": [],
        "requestBody": {
          "description": "Verify's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/VerifyNewlyRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/VerifyNewlyResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {}
          }
        }
      }
    },
    "/users/google": {
      "get": {
        "tags": ["auth"],
        "summary": "registration / login with google",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {}
          },
          "201": {
            "description": "Successful operation",
            "content": {}
          },
          "204": {
            "description": "No Content",
            "content": {}
          }
        }
      }
    },
    "/users/login": {
      "post": {
        "tags": ["auth"],
        "summary": "User login to the system",
        "parameters": [],
        "requestBody": {
          "description": "Login's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserLoginRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserLoginResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized (invalid request body)",
            "content": {}
          }
        }
      }
    },
    "/users/logout": {
      "get": {
        "tags": ["auth"],
        "summary": "User logout",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserLogoutResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized (invalid request body)",
            "content": {}
          }
        }
      }
    },
    "/users/current": {
      "get": {
        "tags": ["auth"],
        "summary": "Refresh user's access",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserCurrentResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized (invalid request body)",
            "content": {}
          }
        }
      }
    },
    "/users": {
      "patch": {
        "tags": ["auth"],
        "summary": "Update information about user",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Patch's object",
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserUpdateRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserUpdateResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": "Unauthorized (invalid request body)",
            "content": {}
          }
        }
      }
    },
    "/news": {
      "get": {
        "tags": ["news"],
        "summary": "petly news",
        "parameters": [
          {
            "in": "query",
            "name": "keyword",
            "schema": {
              "example": "?keyword=cat"
            },
            "description": "search by word (keyword)"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NewsResponse"
                }
              }
            }
          },
          "204": {
            "description": "No Content",
            "content": {}
          }
        }
      }
    },
    "/services": {
      "get": {
        "tags": ["services-sidebar"],
        "summary": "petly's friends",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ServicesResponse"
                }
              }
            }
          },
          "204": {
            "description": "No Content",
            "content": {}
          }
        }
      }
    },
    "/user": {
      "get": {
        "tags": ["user"],
        "summary": "user's information",
        "parameters": [],
        "security": [{ "Bearer Token": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserInfoResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized (invalid request body)",
            "content": {}
          }
        }
      },
      "post": {
        "tags": ["user"],
        "summary": "add user's pet",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/UserAddPetRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserAddPetResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": "Unauthorized (invalid request body)",
            "content": {}
          }
        }
      },
      "delete": {
        "tags": ["user"],
        "summary": "delete user's pet",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserDeletePetRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserDeletePetResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      }
    },
    "/notices/:category": {
      "get": {
        "tags": ["notices"],
        "summary": "get pets by category (sell / lost-found / in-good-hands)",
        "parameters": [
          {
            "in": "query",
            "name": "keyword",
            "schema": {
              "example": "?keyword=cat"
            },
            "description": "search by word (keyword)"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PetsByCategoriesResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {}
          }
        }
      }
    },
    "/notices/favorite": {
      "get": {
        "tags": ["notices"],
        "summary": "get favorite user's pets",
        "parameters": [
          {
            "in": "query",
            "name": "keyword",
            "schema": {
              "example": "?keyword=cat"
            },
            "description": "search by word (keyword)"
          }
        ],
        "security": [{ "Bearer Token": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserFavPetsResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized (invalid request body)",
            "content": {}
          }
        }
      }
    },
    "/notices/mynotices": {
      "get": {
        "tags": ["notices"],
        "summary": "get user's pets",
        "parameters": [
          {
            "in": "query",
            "name": "keyword",
            "schema": {
              "example": "?keyword=cat"
            },
            "description": "search by word (keyword)"
          }
        ],
        "security": [{ "Bearer Token": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserGetPetsResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized (invalid request body)",
            "content": {}
          }
        }
      }
    },
    "/notices/pet/:noticeId": {
      "get": {
        "tags": ["notices"],
        "summary": "get pet by id",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserGetPetResponse"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["notices"],
        "summary": "delete pet from notices (authorized user)",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserDeletePetFromNoticeResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      }
    },
    "/notices/favorite/add/:noticeId": {
      "get": {
        "tags": ["notices"],
        "summary": "add pet to favorite",
        "parameters": [],
        "security": [{ "Bearer Token": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddToFavResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Not Found",
            "content": {}
          }
        }
      }
    },
    "/notices/favorite/remove/:noticeId": {
      "get": {
        "tags": ["notices"],
        "summary": "delete pet from favorite",
        "parameters": [],
        "security": [{ "Bearer Token": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteFromFavResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Not Found",
            "content": {}
          }
        }
      }
    },
    "/notices": {
      "post": {
        "tags": ["notices"],
        "summary": "add pet to notises (authorized user)",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/UserAddPetNoticeRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserAddPetNoticeResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": "Unauthorized (invalid request body)",
            "content": {}
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "UserSignupRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "format": "email"
          },
          "password": {
            "type": "string",
            "example": "1234567"
          },
          "name": {
            "type": "string"
          },
          "place": {
            "type": "string"
          },
          "phone": {
            "type": "string",
            "format": "phone",
            "example": "+380661115577"
          }
        }
      },
      "UserSignupResponse": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "format": "email"
          }
        },
        "example": {
          "email": "user@gmail.com"
        }
      },
      "UserVerifyResponse": {
        "type": "string",
        "example": {
          "message": "Verification successful"
        }
      },
      "VerifyNewlyRequest": {
        "type": "object",
        "required": ["email"],
        "properties": {
          "email": {
            "type": "string",
            "format": "email"
          }
        }
      },
      "VerifyNewlyResponse": {
        "type": "string",
        "example": {
          "message": "Verification email sent"
        }
      },
      "UserNewPasswordRequest": {
        "type": "object",
        "required": ["email"],
        "properties": {
          "email": {
            "type": "string",
            "format": "email"
          }
        }
      },
      "UserNewPasswordResponse": {
        "type": "string",
        "example": {
          "message": "Password updated successfuly"
        }
      },
      "UserLoginRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "format": "email",
            "example": "user@gmail.com"
          },
          "password": {
            "type": "string",
            "example": "1234567"
          }
        }
      },
      "UserLoginResponse": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string"
          },
          "user": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email"
              },
              "avatarURL": {
                "type": "string"
              },
              "dateofbirth": {
                "type": "date",
                "format": "dd.mm.yyyy"
              },
              "favorites": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "_id": {
                "type": "string"
              }
            }
          }
        },
        "example": {
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2YwZGRkNzEyOTY5ZDkxYzIzMjA0ZDciLCJpYXQiOjE2NzY3MzM4NzB9.cdWuv49n5p1zHhtIt8F6CtO-T6zOqaz-5KWIR--9WD4",
          "user": {
            "email": "vikaripka@gmail.com",
            "avatarURL": "//www.gravatar.com/avatar/5a2e862031b7cf673ddfa5bc5dc7e767",
            "dateofbirth": "01.01.1900",
            "favorites": [],
            "_id": "63f0ddd712969d91c23204d7"
          }
        }
      },
      "UserLogoutResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "example": {
          "message": "logout success"
        }
      },
      "UserCurrentResponse": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "format": "email"
          },
          "avatarURL": {
            "type": "string"
          },
          "dateofbirth": {
            "type": "date",
            "format": "dd.mm.yyyy"
          },
          "favorites": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "_id": {
            "type": "string"
          }
        },
        "example": {
          "email": "vikaripka@gmail.com",
          "avatarURL": "//www.gravatar.com/avatar/5a2e862031b7cf673ddfa5bc5dc7e767",
          "dateofbirth": "01.01.1900",
          "favorites": [],
          "_id": "63f0ddd712969d91c23204d7"
        }
      },
      "UserUpdateRequest": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "place": {
            "type": "string",
            "description": "place must conatine two words (ciy and region) and coma"
          },
          "phone": {
            "type": "string",
            "format": "phone",
            "example": "+380661115577"
          },
          "dateofbirth": {
            "type": "string",
            "format": "date",
            "example": "11.12.2000"
          },
          "avatar": {
            "type": "string",
            "format": "binary",
            "description": "user's photo (file png/jpg) "
          }
        }
      },
      "UserUpdateResponse": {
        "type": "object",
        "properties": {
          "place": {
            "type": "string"
          },
          "phone": {
            "type": "string",
            "format": "phone"
          },
          "dateofbirth": {
            "type": "string",
            "format": "dd.mm.yyyy"
          },
          "avatarURL": {
            "type": "string"
          }
        },
        "example": {
          "place": "Kyiv, Ukraine",
          "phone": "+380667547756",
          "dateofbirth": "01.01.1900",
          "avatarURL": "//www.gravatar.com/avatar/5a2e862031b7cf673ddfa5bc5dc7e767"
        }
      },
      "UserInfoResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "description": "success / no content"
          },
          "code": {
            "type": "number",
            "description": "statuc code"
          },
          "result": {
            "type": "object",
            "properties": {
              "data": {
                "type": "object",
                "properties": {
                  "refreshToken": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "verify": {
                    "type": "boolean"
                  },
                  "_id": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string",
                    "formate": "email"
                  },
                  "password": {
                    "type": "string"
                  },
                  "token": {
                    "type": "string"
                  },
                  "avatarURL": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "place": {
                    "type": "string"
                  },
                  "phone": {
                    "type": "string",
                    "formate": "phone"
                  },
                  "dateofbirth": {
                    "type": "string",
                    "format": "dd.mm.yyyy"
                  },
                  "favorites": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "createdAt": {
                    "type": "string"
                  },
                  "updatedAt": {
                    "type": "string"
                  },
                  "__v": {
                    "type": "integer"
                  }
                }
              },
              "pets": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "_id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "date": {
                      "type": "string",
                      "format": "dd.mm.yyyy"
                    },
                    "breed": {
                      "type": "string"
                    },
                    "comment": {
                      "type": "string"
                    },
                    "owner": {
                      "type": "string",
                      "description": "User's unique id"
                    },
                    "createdAt": {
                      "type": "date",
                      "format": "date"
                    },
                    "updatedAt": {
                      "type": "date",
                      "format": "date"
                    }
                  }
                }
              }
            }
          }
        },
        "example": {
          "status": "success",
          "code": 200,
          "result": {
            "data": {
              "refreshToken": [],
              "verify": false,
              "_id": "63e0c4e3730147ed4e3cf5e9",
              "email": "vika@gmail.com",
              "password": "$2b$10$WKu90QOF7tte5X6G/2Uxye7MtbTR1knJLyLY9Wu.op9EMgszEH.nW",
              "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2UwYzRlMzczMDE0N2VkNGUzY2Y1ZTkiLCJjcmVhdGVkQXQiOiIyMDIzLTAyLTA2VDA5OjE0OjExLjk4MloiLCJpYXQiOjE2NzU2NzUwMjd9.LwTFonZ19itrG4oXDa0J9KYINEaNMeyw0Y-jOm5rojQ",
              "avatarURL": "//www.gravatar.com/avatar/320eab812ab24ef3dbaa2e6dc6e024e0",
              "name": "vika",
              "place": "ukraine",
              "phone": "990333555",
              "dateofbirth": "01.01.1900",
              "favorites": [
                "63e636f40d8c9ba686287906",
                "63f14e594090c88a176ba428",
                "63f1004b351cb99420829dcc"
              ],
              "createdAt": "2023-02-06T09:14:11.982Z",
              "updatedAt": "2023-02-06T09:17:07.672Z",
              "__v": 0
            },
            "pets": [
              {
                "_id": "63e0c535730147ed4e3cf5ed",
                "name": "petpet",
                "date": "20.02.2332418",
                "breed": "cat",
                "comment": "it's fat and cute. love it",
                "owner": "63e0c4e3730147ed4e3cf5e9",
                "createdAt": "2023-02-06T09:15:33.367Z",
                "updatedAt": "2023-02-06T09:15:33.367Z"
              }
            ]
          }
        }
      },
      "UserAddPetRequest": {
        "type": "object",
        "required": ["name", "date", "breed", "comment", "avatar"],
        "properties": {
          "name": {
            "type": "string"
          },
          "date": {
            "type": "string",
            "description": "Pet's birtday",
            "format": "dd.mm.yyyy",
            "example": "dd.mm.yyyy"
          },
          "breed": {
            "type": "string"
          },
          "comment": {
            "type": "string"
          },
          "avatar": {
            "type": "string",
            "description": "Pet's photo",
            "format": "binary"
          }
        }
      },
      "UserAddPetResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "code": {
            "type": "number"
          },
          "data": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "date": {
                "type": "string",
                "format": "dd.mm.yyyy"
              },
              "breed": {
                "type": "string"
              },
              "comment": {
                "type": "string"
              },
              "_id": {
                "type": "string"
              },
              "owner": {
                "type": "string"
              },
              "avatarURL": {
                "type": "string"
              }
            }
          }
        },
        "example": {
          "status": "success",
          "code": 201,
          "data": {
            "name": "fitfit",
            "date": "27.05.19",
            "breed": "spaneale",
            "comment": "it's fat and cute. love it",
            "_id": "63f1f1d25d7f57e3b6d4fc69",
            "avatarURL": "https://res.cloudinary.com/dznsyhppg/image/upload/v1676800466/0ec30e21-64b5-473f-bdf9-6ea717acee01.jpg",
            "owner": "63e0c4e3730147ed4e3cf5e9"
          }
        }
      },
      "UserDeletePetRequest": {
        "type": "object",
        "required": ["pet_id"],
        "properties": {
          "pet_id": {
            "type": "string"
          }
        }
      },
      "UserDeletePetResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "code": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          }
        },
        "example": {
          "status": "success",
          "code": 200,
          "message": "pet deleted"
        }
      },
      "ServicesResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "description": "success / no content"
          },
          "code": {
            "type": "number",
            "description": "statuc code"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string"
                },
                "title": {
                  "type": "string"
                },
                "url": {
                  "type": "string"
                },
                "addressUrl": {
                  "type": "string"
                },
                "imageUrl": {
                  "type": "string"
                },
                "address": {
                  "type": "string"
                },
                "workDays": {
                  "type": "aray",
                  "items": {
                    "type": "object",
                    "properties": {
                      "isOpen": {
                        "type": "boolean"
                      },
                      "from": {
                        "type": "string"
                      },
                      "to": {
                        "type": "string"
                      }
                    }
                  }
                },
                "phone": {
                  "type": "string",
                  "format": "phone"
                },
                "email": {
                  "type": "string",
                  "format": "email"
                },
                "createdAt": {
                  "type": "string"
                },
                "updatedAt": {
                  "type": "string"
                }
              }
            }
          }
        },
        "example": {
          "status": "success",
          "code": 200,
          "data": [
            {
              "_id": "63df9e94fcc94723e1d67a64",
              "title": "Притулок для бездомних тварин 'Сіріус'",
              "url": "https://dogcat.com.ua",
              "addressUrl": "https://goo.gl/maps/iq8NXEUf31EAQCzc6",
              "imageUrl": "https://storage.googleapis.com/kidslikev2_bucket/pets-support/images/sponsors/frame_287.png",
              "address": "Fedorivka, Kyiv Oblast, Ukraine, 07372",
              "workDays": [
                {
                  "isOpen": false
                },
                {
                  "isOpen": false
                },
                {
                  "isOpen": false
                },
                {
                  "isOpen": false
                },
                {
                  "isOpen": false
                },
                {
                  "isOpen": true,
                  "from": "11:00",
                  "to": "16:00"
                },
                {
                  "isOpen": true,
                  "from": "11:00",
                  "to": "16:00"
                }
              ],
              "phone": "+380931934069",
              "email": null,
              "createdAt": "2023-02-05T12:18:28.742Z",
              "updatedAt": "2023-02-05T12:18:28.742Z"
            }
          ]
        }
      },
      "NewsResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "description": "success / no content"
          },
          "code": {
            "type": "number",
            "description": "statuc code"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string",
                  "description": "unique id"
                },
                "title": {
                  "type": "string",
                  "description": "title of the article"
                },
                "url": {
                  "type": "string",
                  "description": "link to the article",
                  "format": "url"
                },
                "description": {
                  "type": "string",
                  "description": "link to the article"
                },
                "date": {
                  "type": "string",
                  "description": "date of creation the article",
                  "format": "dd.mm.yyyy"
                }
              }
            }
          }
        },
        "example": {
          "status": "success",
          "code": 200,
          "data": [
            {
              "_id": "63df7435189c36f49fc87845",
              "title": "Чому коти норовлять сунути хвіст в обличчя господаря: кілька причин",
              "url": "https://ukr.media/animals/446231/",
              "description": "Любителі котів зазвичай досконально знають характер своїх пухнастиків. Одних обов'язково потрібно погладити перед їжею, інші чекають, поки ви відкладете книгу, щоб лягти до вас в ліжко. Але іноді коти поводяться так, що навіть досвідчені кошатники не можуть дати пояснення. Наприклад, чому кіт повертається задом до господаря? На перший погляд здається, ніби це акт неповаги. Все-таки така поведінка котів зовсім не схожа на людські норми пристойності. Однак не судіть строго свого улюбленця, поки не розберетеся в причинах. Розповідаємо, чому кіт повертається задом до господаря. Для цього є кілька причин, інформує Ukr. Media.Ввічлива взаємодія",
              "date": "2022-08-13"
            }
          ]
        }
      },
      "PetsByCategoriesResponse": {
        "type": "object",
        "properties": {
          "total_results": {
            "type": "integer"
          },
          "total_pages": {
            "type": "integer"
          },
          "page": {
            "type": "integer"
          },
          "notices": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string"
                },
                "title": {
                  "type": "string"
                },
                "breed": {
                  "type": "string"
                },
                "place": {
                  "type": "string"
                },
                "price": {
                  "type": "string"
                },
                "category": {
                  "type": "string"
                }
              }
            }
          }
        },
        "example": {
          "total_results": 1,
          "total_pages": 1,
          "page": 1,
          "notices": [
            {
              "_id": "63eba2fd2579e96edf54a46d",
              "title": "Cute pet",
              "dateofbirth": "11.05.2022",
              "breed": "labrador",
              "place": "Kyiv, Ukraine",
              "price": 1000,
              "category": "sell",
              "avatarURL": "https://res.cloudinary.com/dznsyhppg/image/upload/v1676387068/4fe5425c-e410-4749-9e08-1f294bd80fe9.webp",
              "owner": "63ea622be4091872cb351aef"
            }
          ]
        }
      },
      "UserFavPetsResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "title": {
              "type": "string"
            },
            "dateofbirth": {
              "type": "string",
              "format": "dd.mm.yyyy"
            },
            "breed": {
              "type": "string"
            },
            "place": {
              "type": "string"
            },
            "category": {
              "type": "string"
            },
            "avatarURL": {
              "type": "string"
            },
            "owner": {
              "type": "string"
            }
          }
        },
        "example": [
          {
            "_id": "63e636f40d8c9ba686287906",
            "title": "cute doggy looking for home",
            "dateofbirth": "01.01.2021",
            "breed": "monkey",
            "place": "street",
            "category": "sell",
            "avatarURL": "https://res.cloudinary.com/dznsyhppg/image/upload/v1676031734/d89d52c8-4add-49c4-a7c9-2446562f5f2f.jpg",
            "owner": "63e49ecb0012cdf5c3c34f85"
          }
        ]
      },
      "UserGetPetsResponse": {
        "type": "object",
        "properties": {
          "total_results": {
            "type": "integer"
          },
          "total_pages": {
            "type": "integer"
          },
          "page": {
            "type": "integer"
          },
          "notices": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string"
                },
                "title": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "dateofbirth": {
                  "type": "string",
                  "format": "dd.mm.yyyy"
                },
                "breed": {
                  "type": "string"
                },
                "place": {
                  "type": "string"
                },
                "sex": {
                  "type": "boolean",
                  "description": "false - male"
                },
                "comments": {
                  "type": "string"
                },
                "category": {
                  "type": "string"
                },
                "avatarURL": {
                  "type": "string"
                },
                "owner": {
                  "type": "string"
                },
                "createdAt": {
                  "type": "string"
                },
                "updatedAt": {
                  "type": "string"
                },
                "__v": {
                  "type": "integer"
                }
              }
            }
          }
        },
        "example": {
          "total_results": 0,
          "total_pages": 0,
          "page": 1,
          "notices": [
            {
              "_id": "63e672af5eccf90307e977cd",
              "title": "found sweet cat",
              "name": "cat",
              "dateofbirth": "11.02.2021",
              "breed": "doesn't have",
              "place": "Kyiv",
              "sex": false,
              "comments": "GOOD CAT",
              "category": "lost-found",
              "avatarURL": "https://res.cloudinary.com/dznsyhppg/image/upload/v1676047022/01c83e25-678f-45df-95eb-dc9412c11dab.jpg",
              "owner": "63e619f2e74bc9b81261d20a",
              "createdAt": "2023-02-10T16:37:03.465Z",
              "updatedAt": "2023-02-10T16:37:03.465Z",
              "__v": 0
            }
          ]
        }
      },
      "UserGetPetResponse": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "dateofbirth": {
            "type": "string",
            "format": "dd.mm.yyyy"
          },
          "breed": {
            "type": "string"
          },
          "place": {
            "type": "string"
          },
          "sex": {
            "type": "boolean",
            "description": "false - male"
          },
          "comments": {
            "type": "string"
          },
          "category": {
            "type": "string"
          },
          "owner": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "__v": {
            "type": "integer"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "phone": {
            "type": "string",
            "format": "phone"
          }
        },
        "example": {
          "_id": "63f2578cdf4c8338b5be2854",
          "title": "gnfdjhbvkdfbvd",
          "name": "dmjfbvkdfbvk",
          "dateofbirth": "23.07.2022",
          "breed": "bdvkfvbkdf",
          "place": "Kyiv,Kyiv",
          "sex": false,
          "comments": "fjshfkjsbfkj",
          "category": "lost-found",
          "owner": "63f25704df4c8338b5be2837",
          "createdAt": "2023-02-19T17:08:28.814Z",
          "updatedAt": "2023-02-19T17:08:28.814Z",
          "__v": 0,
          "email": "gerrraaa1@gmail.com",
          "phone": "+380951270934"
        }
      },
      "UserDeletePetFromNoticeResponse": {
        "type": "string",
        "example": {
          "message": "success"
        }
      },
      "AddToFavResponse": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "dateofbirth": {
            "type": "string",
            "format": "dd.mm.yyyy"
          },
          "breed": {
            "type": "string"
          },
          "place": {
            "type": "string"
          },
          "price": {
            "type": "string"
          },
          "sex": {
            "type": "boolean",
            "description": "false - male"
          },
          "comments": {
            "type": "string"
          },
          "category": {
            "type": "string"
          },
          "owner": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "__v": {
            "type": "integer"
          }
        },
        "example": {
          "_id": "63f14e594090c88a176ba428",
          "title": "cxxc",
          "name": "Rosie Simpson",
          "dateofbirth": "29.01.2023",
          "breed": "fffffff",
          "place": "ukraine, Kyyai",
          "price": 3,
          "sex": true,
          "comments": "ddddd hhhhh hhhhh",
          "category": "sell",
          "owner": "63ea620ae4091872cb351ad7",
          "createdAt": "2023-02-18T22:16:57.214Z",
          "updatedAt": "2023-02-18T22:16:57.214Z",
          "__v": 0
        }
      },
      "DeleteFromFavResponse": {
        "type": "string",
        "example": {
          "message": "success"
        }
      },
      "UserAddPetNoticeRequest": {
        "type": "object",
        "required": ["title", "place", "price", "sex", "category"],
        "properties": {
          "title": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "place": {
            "type": "string"
          },
          "dateofbirth": {
            "type": "string",
            "format": "dd.mm.yyyy"
          },
          "breed": {
            "type": "string"
          },
          "price": {
            "type": "string"
          },
          "sex": {
            "type": "boolean",
            "description": "false - male"
          },
          "comments": {
            "type": "string"
          },
          "category": {
            "type": "string",
            "description": "sell'/lost-found/in-good-hands"
          },
          "avatar": {
            "type": "string",
            "description": "Pet's photo",
            "format": "binary"
          }
        }
      },
      "UserAddPetNoticeResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "dateofbirth": {
              "type": "string",
              "format": "dd.mm.yyyy"
            },
            "breed": {
              "type": "string"
            },
            "place": {
              "type": "string"
            },
            "price": {
              "type": "string"
            },
            "sex": {
              "type": "boolean",
              "description": "false - male"
            },
            "comments": {
              "type": "string"
            },
            "category": {
              "type": "string",
              "description": "sell'/lost-found/in-good-hands"
            },
            "avatarURL": {
              "type": "string"
            },
            "owner": {
              "type": "string"
            },
            "_id": {
              "type": "string"
            },
            "createdAt": {
              "type": "string"
            },
            "updatedAt": {
              "type": "string"
            },
            "__v": {
              "type": "integer"
            }
          }
        },
        "example": {
          "title": "found sweet cat",
          "name": "cat",
          "dateofbirth": "11.02.2021",
          "breed": "doesn't have",
          "place": "Kyiv",
          "price": "-",
          "sex": false,
          "comments": "GOOD CAT",
          "category": "lost-found",
          "avatarURL": "https://res.cloudinary.com/dznsyhppg/image/upload/v1676047022/01c83e25-678f-45df-95eb-dc9412c11dab.jpg",
          "owner": "63e619f2e74bc9b81261d20a",
          "_id": "63e672af5eccf90307e977cd",
          "createdAt": "2023-02-10T16:37:03.465Z",
          "updatedAt": "2023-02-10T16:37:03.465Z",
          "__v": 0
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
